swagger: "2.0"
info:
    description: Sample API for Widgets
    title: Widgets API
    version: 1.0.0
consumes:
    - application/json
produces:
    - application/json
schemes:
    - http
paths:
    /widgets:
        get:
            tags:
                - widgets
            operationId: listWidgets
            parameters:
                - name: limit
                  in: query
                  type: integer
                  format: int32
                  default: 20
            responses:
                200:
                    description: List of widgets
                    schema:
                        type: array
                        items:
                            $ref: "#/definitions/widget"
                default:
                    description: Generic error response
                    schema:
                        $ref: "#/definitions/error"
        post:
            tags:
                - widgets
            operationId: createWidget
            parameters:
                - name: body
                  in: body
                  schema:
                      $ref: "#/definitions/widget"
            responses:
                201:
                    description: Widget created successfully
                    schema:
                        $ref: "#/definitions/widget"
                default:
                    description: Error response
                    schema:
                        $ref: "#/definitions/error"
    /widgets/{id}:
        parameters:
            - type: integer
              format: int64
              name: id
              in: path
              required: true
        get:
            tags:
                - widgets
            operationId: getWidget
            responses:
                200:
                    description: Widget details
                    schema:
                        $ref: "#/definitions/widget"
                default:
                    description: Error response
                    schema:
                        $ref: "#/definitions/error"
        put:
            tags:
                - widgets
            operationId: updateWidget
            parameters:
                - name: id
                  in: path
                  type: integer
                  format: int64
                  required: true
                - name: body
                  in: body
                  schema:
                      $ref: "#/definitions/widget"
            responses:
                200:
                    description: Widget updated successfully
                    schema:
                        $ref: "#/definitions/widget"
                default:
                    description: Error response
                    schema:
                        $ref: "#/definitions/error"
        delete:
            tags:
                - widgets
            operationId: deleteWidget
            parameters:
                - name: id
                  in: path
                  type: integer
                  format: int64
                  required: true
            responses:
                204:
                    description: Widget deleted successfully
                default:
                    description: Error response
                    schema:
                        $ref: "#/definitions/error"
definitions:
    widget:
        type: object
        properties:
            id:
                type: integer
                format: int64
            name:
                type: string
            description:
                type: string
    error:
        type: object
        properties:
            code:
                type: integer
                format: int64
            message:
                type: string