// Code generated by go-swagger; DO NOT EDIT.

package widgets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Artyem-Y/widgets-sdk-client/models"
)

// CreateWidgetReader is a Reader for the CreateWidget structure.
type CreateWidgetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateWidgetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateWidgetCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateWidgetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateWidgetCreated creates a CreateWidgetCreated with default headers values
func NewCreateWidgetCreated() *CreateWidgetCreated {
	return &CreateWidgetCreated{}
}

/*
CreateWidgetCreated describes a response with status code 201, with default header values.

Widget created successfully
*/
type CreateWidgetCreated struct {
	Payload *models.Widget
}

// IsSuccess returns true when this create widget created response has a 2xx status code
func (o *CreateWidgetCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create widget created response has a 3xx status code
func (o *CreateWidgetCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create widget created response has a 4xx status code
func (o *CreateWidgetCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create widget created response has a 5xx status code
func (o *CreateWidgetCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create widget created response a status code equal to that given
func (o *CreateWidgetCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create widget created response
func (o *CreateWidgetCreated) Code() int {
	return 201
}

func (o *CreateWidgetCreated) Error() string {
	return fmt.Sprintf("[POST /widgets][%d] createWidgetCreated  %+v", 201, o.Payload)
}

func (o *CreateWidgetCreated) String() string {
	return fmt.Sprintf("[POST /widgets][%d] createWidgetCreated  %+v", 201, o.Payload)
}

func (o *CreateWidgetCreated) GetPayload() *models.Widget {
	return o.Payload
}

func (o *CreateWidgetCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Widget)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateWidgetDefault creates a CreateWidgetDefault with default headers values
func NewCreateWidgetDefault(code int) *CreateWidgetDefault {
	return &CreateWidgetDefault{
		_statusCode: code,
	}
}

/*
CreateWidgetDefault describes a response with status code -1, with default header values.

Error response
*/
type CreateWidgetDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this create widget default response has a 2xx status code
func (o *CreateWidgetDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this create widget default response has a 3xx status code
func (o *CreateWidgetDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this create widget default response has a 4xx status code
func (o *CreateWidgetDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this create widget default response has a 5xx status code
func (o *CreateWidgetDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this create widget default response a status code equal to that given
func (o *CreateWidgetDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the create widget default response
func (o *CreateWidgetDefault) Code() int {
	return o._statusCode
}

func (o *CreateWidgetDefault) Error() string {
	return fmt.Sprintf("[POST /widgets][%d] createWidget default  %+v", o._statusCode, o.Payload)
}

func (o *CreateWidgetDefault) String() string {
	return fmt.Sprintf("[POST /widgets][%d] createWidget default  %+v", o._statusCode, o.Payload)
}

func (o *CreateWidgetDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateWidgetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
