// Code generated by go-swagger; DO NOT EDIT.

package widgets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"terraform-provider-hashicups-pf/models"
)

// NewCreateWidgetParams creates a new CreateWidgetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateWidgetParams() *CreateWidgetParams {
	return &CreateWidgetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateWidgetParamsWithTimeout creates a new CreateWidgetParams object
// with the ability to set a timeout on a request.
func NewCreateWidgetParamsWithTimeout(timeout time.Duration) *CreateWidgetParams {
	return &CreateWidgetParams{
		timeout: timeout,
	}
}

// NewCreateWidgetParamsWithContext creates a new CreateWidgetParams object
// with the ability to set a context for a request.
func NewCreateWidgetParamsWithContext(ctx context.Context) *CreateWidgetParams {
	return &CreateWidgetParams{
		Context: ctx,
	}
}

// NewCreateWidgetParamsWithHTTPClient creates a new CreateWidgetParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateWidgetParamsWithHTTPClient(client *http.Client) *CreateWidgetParams {
	return &CreateWidgetParams{
		HTTPClient: client,
	}
}

/*
CreateWidgetParams contains all the parameters to send to the API endpoint

	for the create widget operation.

	Typically these are written to a http.Request.
*/
type CreateWidgetParams struct {

	// Body.
	Body *models.Widget

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create widget params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateWidgetParams) WithDefaults() *CreateWidgetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create widget params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateWidgetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create widget params
func (o *CreateWidgetParams) WithTimeout(timeout time.Duration) *CreateWidgetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create widget params
func (o *CreateWidgetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create widget params
func (o *CreateWidgetParams) WithContext(ctx context.Context) *CreateWidgetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create widget params
func (o *CreateWidgetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create widget params
func (o *CreateWidgetParams) WithHTTPClient(client *http.Client) *CreateWidgetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create widget params
func (o *CreateWidgetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create widget params
func (o *CreateWidgetParams) WithBody(body *models.Widget) *CreateWidgetParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create widget params
func (o *CreateWidgetParams) SetBody(body *models.Widget) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateWidgetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
