// Code generated by go-swagger; DO NOT EDIT.

package widgets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteWidgetParams creates a new DeleteWidgetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteWidgetParams() *DeleteWidgetParams {
	return &DeleteWidgetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteWidgetParamsWithTimeout creates a new DeleteWidgetParams object
// with the ability to set a timeout on a request.
func NewDeleteWidgetParamsWithTimeout(timeout time.Duration) *DeleteWidgetParams {
	return &DeleteWidgetParams{
		timeout: timeout,
	}
}

// NewDeleteWidgetParamsWithContext creates a new DeleteWidgetParams object
// with the ability to set a context for a request.
func NewDeleteWidgetParamsWithContext(ctx context.Context) *DeleteWidgetParams {
	return &DeleteWidgetParams{
		Context: ctx,
	}
}

// NewDeleteWidgetParamsWithHTTPClient creates a new DeleteWidgetParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteWidgetParamsWithHTTPClient(client *http.Client) *DeleteWidgetParams {
	return &DeleteWidgetParams{
		HTTPClient: client,
	}
}

/*
DeleteWidgetParams contains all the parameters to send to the API endpoint

	for the delete widget operation.

	Typically these are written to a http.Request.
*/
type DeleteWidgetParams struct {

	// ID.
	//
	// Format: int64
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete widget params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteWidgetParams) WithDefaults() *DeleteWidgetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete widget params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteWidgetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete widget params
func (o *DeleteWidgetParams) WithTimeout(timeout time.Duration) *DeleteWidgetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete widget params
func (o *DeleteWidgetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete widget params
func (o *DeleteWidgetParams) WithContext(ctx context.Context) *DeleteWidgetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete widget params
func (o *DeleteWidgetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete widget params
func (o *DeleteWidgetParams) WithHTTPClient(client *http.Client) *DeleteWidgetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete widget params
func (o *DeleteWidgetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete widget params
func (o *DeleteWidgetParams) WithID(id int64) *DeleteWidgetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete widget params
func (o *DeleteWidgetParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteWidgetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
