// Code generated by go-swagger; DO NOT EDIT.

package widgets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetWidgetParams creates a new GetWidgetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetWidgetParams() *GetWidgetParams {
	return &GetWidgetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetWidgetParamsWithTimeout creates a new GetWidgetParams object
// with the ability to set a timeout on a request.
func NewGetWidgetParamsWithTimeout(timeout time.Duration) *GetWidgetParams {
	return &GetWidgetParams{
		timeout: timeout,
	}
}

// NewGetWidgetParamsWithContext creates a new GetWidgetParams object
// with the ability to set a context for a request.
func NewGetWidgetParamsWithContext(ctx context.Context) *GetWidgetParams {
	return &GetWidgetParams{
		Context: ctx,
	}
}

// NewGetWidgetParamsWithHTTPClient creates a new GetWidgetParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetWidgetParamsWithHTTPClient(client *http.Client) *GetWidgetParams {
	return &GetWidgetParams{
		HTTPClient: client,
	}
}

/*
GetWidgetParams contains all the parameters to send to the API endpoint

	for the get widget operation.

	Typically these are written to a http.Request.
*/
type GetWidgetParams struct {

	// ID.
	//
	// Format: int64
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get widget params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWidgetParams) WithDefaults() *GetWidgetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get widget params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWidgetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get widget params
func (o *GetWidgetParams) WithTimeout(timeout time.Duration) *GetWidgetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get widget params
func (o *GetWidgetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get widget params
func (o *GetWidgetParams) WithContext(ctx context.Context) *GetWidgetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get widget params
func (o *GetWidgetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get widget params
func (o *GetWidgetParams) WithHTTPClient(client *http.Client) *GetWidgetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get widget params
func (o *GetWidgetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get widget params
func (o *GetWidgetParams) WithID(id int64) *GetWidgetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get widget params
func (o *GetWidgetParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetWidgetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
