// Code generated by go-swagger; DO NOT EDIT.

package widgets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListWidgetsParams creates a new ListWidgetsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListWidgetsParams() *ListWidgetsParams {
	return &ListWidgetsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListWidgetsParamsWithTimeout creates a new ListWidgetsParams object
// with the ability to set a timeout on a request.
func NewListWidgetsParamsWithTimeout(timeout time.Duration) *ListWidgetsParams {
	return &ListWidgetsParams{
		timeout: timeout,
	}
}

// NewListWidgetsParamsWithContext creates a new ListWidgetsParams object
// with the ability to set a context for a request.
func NewListWidgetsParamsWithContext(ctx context.Context) *ListWidgetsParams {
	return &ListWidgetsParams{
		Context: ctx,
	}
}

// NewListWidgetsParamsWithHTTPClient creates a new ListWidgetsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListWidgetsParamsWithHTTPClient(client *http.Client) *ListWidgetsParams {
	return &ListWidgetsParams{
		HTTPClient: client,
	}
}

/*
ListWidgetsParams contains all the parameters to send to the API endpoint

	for the list widgets operation.

	Typically these are written to a http.Request.
*/
type ListWidgetsParams struct {

	// Limit.
	//
	// Format: int32
	// Default: 20
	Limit *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list widgets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListWidgetsParams) WithDefaults() *ListWidgetsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list widgets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListWidgetsParams) SetDefaults() {
	var (
		limitDefault = int32(20)
	)

	val := ListWidgetsParams{
		Limit: &limitDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the list widgets params
func (o *ListWidgetsParams) WithTimeout(timeout time.Duration) *ListWidgetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list widgets params
func (o *ListWidgetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list widgets params
func (o *ListWidgetsParams) WithContext(ctx context.Context) *ListWidgetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list widgets params
func (o *ListWidgetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list widgets params
func (o *ListWidgetsParams) WithHTTPClient(client *http.Client) *ListWidgetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list widgets params
func (o *ListWidgetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the list widgets params
func (o *ListWidgetsParams) WithLimit(limit *int32) *ListWidgetsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list widgets params
func (o *ListWidgetsParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WriteToRequest writes these params to a swagger request
func (o *ListWidgetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int32

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
