// Code generated by go-swagger; DO NOT EDIT.

package widgets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Artyem-Y/widgets-sdk-client/models"
)

// ListWidgetsReader is a Reader for the ListWidgets structure.
type ListWidgetsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListWidgetsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListWidgetsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListWidgetsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListWidgetsOK creates a ListWidgetsOK with default headers values
func NewListWidgetsOK() *ListWidgetsOK {
	return &ListWidgetsOK{}
}

/*
ListWidgetsOK describes a response with status code 200, with default header values.

List of widgets
*/
type ListWidgetsOK struct {
	Payload []*models.Widget
}

// IsSuccess returns true when this list widgets o k response has a 2xx status code
func (o *ListWidgetsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list widgets o k response has a 3xx status code
func (o *ListWidgetsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list widgets o k response has a 4xx status code
func (o *ListWidgetsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list widgets o k response has a 5xx status code
func (o *ListWidgetsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list widgets o k response a status code equal to that given
func (o *ListWidgetsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list widgets o k response
func (o *ListWidgetsOK) Code() int {
	return 200
}

func (o *ListWidgetsOK) Error() string {
	return fmt.Sprintf("[GET /widgets][%d] listWidgetsOK  %+v", 200, o.Payload)
}

func (o *ListWidgetsOK) String() string {
	return fmt.Sprintf("[GET /widgets][%d] listWidgetsOK  %+v", 200, o.Payload)
}

func (o *ListWidgetsOK) GetPayload() []*models.Widget {
	return o.Payload
}

func (o *ListWidgetsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListWidgetsDefault creates a ListWidgetsDefault with default headers values
func NewListWidgetsDefault(code int) *ListWidgetsDefault {
	return &ListWidgetsDefault{
		_statusCode: code,
	}
}

/*
ListWidgetsDefault describes a response with status code -1, with default header values.

Generic error response
*/
type ListWidgetsDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this list widgets default response has a 2xx status code
func (o *ListWidgetsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list widgets default response has a 3xx status code
func (o *ListWidgetsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list widgets default response has a 4xx status code
func (o *ListWidgetsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list widgets default response has a 5xx status code
func (o *ListWidgetsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list widgets default response a status code equal to that given
func (o *ListWidgetsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list widgets default response
func (o *ListWidgetsDefault) Code() int {
	return o._statusCode
}

func (o *ListWidgetsDefault) Error() string {
	return fmt.Sprintf("[GET /widgets][%d] listWidgets default  %+v", o._statusCode, o.Payload)
}

func (o *ListWidgetsDefault) String() string {
	return fmt.Sprintf("[GET /widgets][%d] listWidgets default  %+v", o._statusCode, o.Payload)
}

func (o *ListWidgetsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListWidgetsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
