// Code generated by go-swagger; DO NOT EDIT.

package widgets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Artyem-Y/widgets-sdk-client/models"
)

// UpdateWidgetReader is a Reader for the UpdateWidget structure.
type UpdateWidgetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateWidgetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateWidgetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUpdateWidgetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateWidgetOK creates a UpdateWidgetOK with default headers values
func NewUpdateWidgetOK() *UpdateWidgetOK {
	return &UpdateWidgetOK{}
}

/*
UpdateWidgetOK describes a response with status code 200, with default header values.

Widget updated successfully
*/
type UpdateWidgetOK struct {
	Payload *models.Widget
}

// IsSuccess returns true when this update widget o k response has a 2xx status code
func (o *UpdateWidgetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update widget o k response has a 3xx status code
func (o *UpdateWidgetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update widget o k response has a 4xx status code
func (o *UpdateWidgetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update widget o k response has a 5xx status code
func (o *UpdateWidgetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update widget o k response a status code equal to that given
func (o *UpdateWidgetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update widget o k response
func (o *UpdateWidgetOK) Code() int {
	return 200
}

func (o *UpdateWidgetOK) Error() string {
	return fmt.Sprintf("[PUT /widgets/{id}][%d] updateWidgetOK  %+v", 200, o.Payload)
}

func (o *UpdateWidgetOK) String() string {
	return fmt.Sprintf("[PUT /widgets/{id}][%d] updateWidgetOK  %+v", 200, o.Payload)
}

func (o *UpdateWidgetOK) GetPayload() *models.Widget {
	return o.Payload
}

func (o *UpdateWidgetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Widget)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateWidgetDefault creates a UpdateWidgetDefault with default headers values
func NewUpdateWidgetDefault(code int) *UpdateWidgetDefault {
	return &UpdateWidgetDefault{
		_statusCode: code,
	}
}

/*
UpdateWidgetDefault describes a response with status code -1, with default header values.

Error response
*/
type UpdateWidgetDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this update widget default response has a 2xx status code
func (o *UpdateWidgetDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this update widget default response has a 3xx status code
func (o *UpdateWidgetDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this update widget default response has a 4xx status code
func (o *UpdateWidgetDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this update widget default response has a 5xx status code
func (o *UpdateWidgetDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this update widget default response a status code equal to that given
func (o *UpdateWidgetDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the update widget default response
func (o *UpdateWidgetDefault) Code() int {
	return o._statusCode
}

func (o *UpdateWidgetDefault) Error() string {
	return fmt.Sprintf("[PUT /widgets/{id}][%d] updateWidget default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateWidgetDefault) String() string {
	return fmt.Sprintf("[PUT /widgets/{id}][%d] updateWidget default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateWidgetDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateWidgetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
