// Code generated by go-swagger; DO NOT EDIT.

package widgets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"test/widgets-sdk-client/models"
)

// NewUpdateWidgetParams creates a new UpdateWidgetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateWidgetParams() *UpdateWidgetParams {
	return &UpdateWidgetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateWidgetParamsWithTimeout creates a new UpdateWidgetParams object
// with the ability to set a timeout on a request.
func NewUpdateWidgetParamsWithTimeout(timeout time.Duration) *UpdateWidgetParams {
	return &UpdateWidgetParams{
		timeout: timeout,
	}
}

// NewUpdateWidgetParamsWithContext creates a new UpdateWidgetParams object
// with the ability to set a context for a request.
func NewUpdateWidgetParamsWithContext(ctx context.Context) *UpdateWidgetParams {
	return &UpdateWidgetParams{
		Context: ctx,
	}
}

// NewUpdateWidgetParamsWithHTTPClient creates a new UpdateWidgetParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateWidgetParamsWithHTTPClient(client *http.Client) *UpdateWidgetParams {
	return &UpdateWidgetParams{
		HTTPClient: client,
	}
}

/*
UpdateWidgetParams contains all the parameters to send to the API endpoint

	for the update widget operation.

	Typically these are written to a http.Request.
*/
type UpdateWidgetParams struct {

	// Body.
	Body *models.Widget

	// ID.
	//
	// Format: int64
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update widget params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateWidgetParams) WithDefaults() *UpdateWidgetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update widget params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateWidgetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update widget params
func (o *UpdateWidgetParams) WithTimeout(timeout time.Duration) *UpdateWidgetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update widget params
func (o *UpdateWidgetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update widget params
func (o *UpdateWidgetParams) WithContext(ctx context.Context) *UpdateWidgetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update widget params
func (o *UpdateWidgetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update widget params
func (o *UpdateWidgetParams) WithHTTPClient(client *http.Client) *UpdateWidgetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update widget params
func (o *UpdateWidgetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update widget params
func (o *UpdateWidgetParams) WithBody(body *models.Widget) *UpdateWidgetParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update widget params
func (o *UpdateWidgetParams) SetBody(body *models.Widget) {
	o.Body = body
}

// WithID adds the id to the update widget params
func (o *UpdateWidgetParams) WithID(id int64) *UpdateWidgetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update widget params
func (o *UpdateWidgetParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateWidgetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
